version: '3.8'

services:
  postgres:
    container_name: nest-clean-pg
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest-clear
      PGDATA: data/postgres
    volumes:
      - ./data/pg:/data/postgres
